// Prepares the vendor files that are served from the site itself (run by `npm run build:css`):
//  1. src/vendor/icons.css — every fa-* icon the site uses, as an SVG mask embedded in CSS. The markup
//     keeps Font Awesome's classes (<i class="fas fa-home">) but no icon font is downloaded (the solid +
//     brands fonts were ~260 KB). Icons: Font Awesome Free SVGs, CC BY 4.0.
//  2. assets/vendor/aos.js — AOS hides [data-aos] content until its script runs, so its CSS (bundled
//     into tailwind.css) and JS must come from the same place: a CDN outage must not blank the page.
//  3. src/vendor/fonts.css + assets/fonts/ — the Tajawal weights in use (OFL), self-hosted so no
//     third-party stylesheet blocks the first render (and no request goes to Google Fonts).
import { copyFile, mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { ROOT } from './cdn-assets.mjs';

const PKG = join(ROOT, 'node_modules/@fortawesome/fontawesome-free');
const { version } = JSON.parse(await readFile(join(PKG, 'package.json'), 'utf8'));
const families = JSON.parse(await readFile(join(PKG, 'metadata/icon-families.json'), 'utf8'));
// Classes that are styles/utilities, not icons
const UTILITIES = new Set(['solid', 'brands', 'regular', 'spin', 'fw']);

const alias = {};
for (const [name, meta] of Object.entries(families)) {
    for (const old of meta.aliases?.names || []) alias[old] = name;
}

const sources = ['index.html', 'script.js', ...(await readdir(join(ROOT, 'js'))).map(f => `js/${f}`)];
const used = new Set();
for (const file of sources) {
    for (const [, name] of (await readFile(join(ROOT, file), 'utf8')).matchAll(/\bfa-([a-z0-9-]+)/g)) {
        if (!UTILITIES.has(name)) used.add(name);
    }
}

async function svgFor(name) {
    const canonical = alias[name] || name;
    for (const style of ['solid', 'brands', 'regular']) {
        try { return await readFile(join(PKG, 'svgs', style, `${canonical}.svg`), 'utf8'); } catch { /* try next */ }
    }
    throw new Error(`Unknown Font Awesome icon: fa-${name}`);
}

const rules = [];
for (const name of [...used].sort()) {
    const svg = await svgFor(name);
    const width = Number(svg.match(/viewBox="0 0 (\d+) 512"/)[1]);
    const path = svg.match(/<path d="([^"]+)"/)[1];
    const uri = `<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 ${width} 512'><path d='${path}'/></svg>`
        .replace(/</g, '%3C').replace(/>/g, '%3E').replace(/#/g, '%23');
    const w = width === 512 ? '' : ` --fa-w: ${+(width / 512).toFixed(4)}em;`;
    rules.push(`.fa-${name} { --fa-icon: url("data:image/svg+xml,${uri}");${w} }`);
}

const css = `/*! Icons: Font Awesome Free ${version} by @fontawesome - https://fontawesome.com
 * License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Code: MIT License)
 * Copyright 2023 Fonticons, Inc. — generated by scripts/build-icons.mjs, do not edit */
.fa, .fas, .fab, .far, .fa-solid, .fa-brands, .fa-regular { display: inline-block; font-style: normal; line-height: 1; }
.fa::before, .fas::before, .fab::before, .far::before, .fa-solid::before, .fa-brands::before, .fa-regular::before {
  content: ""; display: inline-block; width: var(--fa-w, 1em); height: 1em; vertical-align: -0.125em;
  background-color: currentColor;
  -webkit-mask: var(--fa-icon) center / contain no-repeat; mask: var(--fa-icon) center / contain no-repeat;
}
.fa-spin { animation: fa-spin 2s linear infinite; }
@keyframes fa-spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }
@media (prefers-reduced-motion: reduce) { .fa-spin { animation: none; } }
${rules.join('\n')}
`;
await mkdir(join(ROOT, 'src/vendor'), { recursive: true });
await writeFile(join(ROOT, 'src/vendor/icons.css'), css);
console.log(`icons.css: ${used.size} icons`);

const AOS = join(ROOT, 'node_modules/aos');
const aosVersion = JSON.parse(await readFile(join(AOS, 'package.json'), 'utf8')).version;
await mkdir(join(ROOT, 'assets/vendor'), { recursive: true });
await copyFile(join(AOS, 'dist/aos.js'), join(ROOT, 'assets/vendor/aos.js'));
console.log(`assets/vendor/aos.js: aos@${aosVersion}`);

const FONT = join(ROOT, 'node_modules/@fontsource/tajawal');
const WEIGHTS = [400, 500, 700, 800];          // font-normal/medium/bold/extrabold in the markup
await mkdir(join(ROOT, 'assets/fonts'), { recursive: true });
const faces = [];
for (const weight of WEIGHTS) {
    const css = await readFile(join(FONT, `${weight}.css`), 'utf8');
    for (const [face] of css.matchAll(/@font-face\s*{[^}]+}/g)) {
        const file = face.match(/url\(\.\/files\/([^)]+\.woff2)\)/)[1];
        await copyFile(join(FONT, 'files', file), join(ROOT, 'assets/fonts', file));
        faces.push(face.replace(/src:[^;]+;/, `src: url("../fonts/${file}") format("woff2");`));
    }
}
const fontVersion = JSON.parse(await readFile(join(FONT, 'package.json'), 'utf8')).version;
await writeFile(join(ROOT, 'src/vendor/fonts.css'),
    `/*! Tajawal (SIL Open Font License 1.1) via @fontsource/tajawal ${fontVersion} — generated by scripts/build-vendor.mjs */\n${faces.join('\n')}\n`);
console.log(`fonts.css: Tajawal ${WEIGHTS.join('/')} (${faces.length} faces)`);
